### ISSUE TITLE
i know wrong place but can you take a look at...

### ISSUE THREAD

**Issue by loordgek** [flow/caustic#24]
https://github.com/NOVA-Team it is sort off dead if you make a pr it gets sill responds 
can you work take it over or join the team ???

**Comment by loordgek** [comment]
i realy hope you take a look at it

**Comment by lukespragg** [comment]
The flow projects are just generic libraries. Pretty sure the original authors would be best for working on the other project.

**Comment by loordgek** [comment]
they have no time for it :( i did hope for some thing else then this
and NOVA is a "generic" voxel api

**Comment by lukespragg** [comment]
I know what it is, it's basically the same thing that I spent 3 years on before, as did most of the others here. ;)
